Repository LibVNC/libvncserver, pull requests merged in 2021-09, with the labels that each got.

#480 libvncclient: implement UltraVNC's MSLogonII authentication scheme
  libvncclient/rfbproto.c
  rfb/rfbproto.h
Labels: enhancement

#472 CMake: Add the generation of cmake configuration files to apply to find_package
  CMakeLists.txt
  cmake/Modules/LibVNCServerConfig.cmake.in
Labels: building, response-needed, enhancement

#481 README: document how to use in common buildsystems
  README.md
Labels: doc-improve
